/*
 * Loan Calculator
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LoanRepaymentsAmountOwing struct {

	Year int32 `json:"year,omitempty"`

	Interest int32 `json:"interest,omitempty"`

	Principal int32 `json:"principal,omitempty"`

	Total int32 `json:"total,omitempty"`
}
