/*
 * Loan Calculator
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LoanRepayments struct {

	MonthlyRepayments int32 `json:"monthly_repayments,omitempty"`

	TotalInterestPayable int32 `json:"total_interest_payable,omitempty"`

	AmountOwing []LoanRepaymentsAmountOwing `json:"amount_owing,omitempty"`
}
